### ISSUE TITLE
Fails to compile

### ISSUE THREAD

**Issue by joelgombin** [rstudio/bookdown-demo#1]
When I try to compile (by hitting the button "Knit" in RStudio), I get this error:

```
Quitting from lines 55-88 (book.Rmd) 
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  objet 'is_html_output' introuvable
Calls: <Anonymous> ... inline_exec -> withVisible -> eval -> eval -> ::: -> get
Exécution arrêtée
```

OS : Ubuntu 14.04
RStudio version: 0.99.825
R version: 3.2.2
knitr version: 1.11
bookdown version: 0.0.5
pandoc version: 1.13.1

Any idea what's goign wrong?

**Comment by hadley** [comment]
You need the development version of knitr

**Comment by psolymos** [comment]
Hey Folks, I had the same issue and figured out that I needed knitr v1.15 (a new knitr option for timings I think). Maybe highlight it on the bookdown website? https://bookdown.org/

**Comment by yihui** [comment]
@psolymos knitr 1.15 should be automatically installed when you `install.packages('bookdown')`. Anyway, [again](https://github.com/rstudio/bookdown/issues/235#issuecomment-257065554), when in doubt, `update.packages()` :)

**Comment by psolymos** [comment]
Thanks @yihui , somehow it did not update automatically (maybe it was already loaded in my session) and just wanted to leave a trail.

**Comment by yihui** [comment]
Okay, I see. Thanks @psolymos
