### ISSUE TITLE
post-processing LaTeX files

### ISSUE THREAD

**Issue by topepo** [rstudio/bookdown-demo#10]
The package is fantastic. Great job. 

I'm moving my [package documentation](http://topepo.github.io/caret/index.html) over to bookdown and looking to write the next book using it. For a book, the end format is a LaTeX file using the publisher's style files. 

I had three questions...

1) get the `tex` files

 >  Leave the job of careful typesetting to the very end (ideally after you have really finished the content of the book).

That would be the plan but I'm unclear as to how to get there. If we use markdown as the format, `pandoc` looks like it does a conversion from md to LaTeX

 > `/usr/local/bin/pandoc +RTS -K512m -RTS _main.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output _main.tex ...`

I don't see any way to get the resulting `tex` files even with 
```r
bookdown::render_book('index.Rmd', 'bookdown::pdf_book', clean = FALSE)
```
2) Is there indexing in bookdown? I think that I would just add the `index` LaTeX citations at the end after the content is finalized but would like to her what you think. 

3) I don't see a way to do a bibliography at the end of the document (as if it were another chapter).  Any advice there? 

Thanks,

Max

**Comment by yihui** [comment]
I have tested the LaTeX styles of Springer and Chapman & Hall/CRC. You can see the Springer example here http://stackoverflow.com/q/38599036/559676 To answer your first question, you can use

```yaml
bookdown::pdf_book:
  keep_tex: yes
```

The second question was also answered there (also see https://github.com/rstudio/bookdown/issues/149).

For the third question, do you mean per-chapter bibliographies? It seems you can find a lot of possible solutions with Google searches.

**Comment by topepo** [comment]
I think that answers my questions. Thanks
