### ISSUE TITLE
custom js

### ISSUE THREAD

**Issue by jeroenooms** [rstudio/bookdown-demo#13]
Is there a standard way to add custom javascript to html output? Similar to `style.css` but then javascript?

**Comment by yihui** [comment]
Yes, you can use the `includes` option: https://bookdown.org/yihui/bookdown/yaml-options.html It is inherited from `rmarkdown::html_document`: http://rmarkdown.rstudio.com/html_document_format.html#includes

**Comment by jeroenooms** [comment]
Thank you!

**Comment by jeroenooms** [comment]
Perhaps add this to the demo?

**Comment by yihui** [comment]
I'm not sure. This demo is supposed to be a starting point, and it is probably not very common for beginners to add custom JS to the book.

**Comment by jeroenooms** [comment]
OK that makes sense. It's difficult to these options though, if not by example.
