### ISSUE TITLE
RStudio 'knitr' button generates PDF output only

### ISSUE THREAD

**Issue by slonik-az** [rstudio/bookdown-demo#14]
I installed bookdown-demo as described in the documentation.
Whenever I click 'knitr' button I am only getting PDF output and pdf viewer but no html. I only can generate HTML output by going to 'Build' tab and then choosing 'bookdown::gitbook' from under 'Build Book' dropdown menu.

I am running the latest RStudio 1.0.136 under Mac OS X El Capitain and latest bookdown from github installed via devtools.

--Leo

**Comment by yihui** [comment]
RStudio will remember your last choice in the Build menu. I believe all formats should be built if you click `All Formats` in the menu:

![image](https://cloud.githubusercontent.com/assets/163582/23641008/a4465ae6-02b6-11e7-8803-98ce5b62365c.png)

**Comment by slonik-az** [comment]
Thanks for a fast reply. But, unfortunately, my RStudio (macosx) does not remember the last choice in 'Build Book'. If I click knitr button it always  produces a PDF file.

**Comment by yihui** [comment]
I think it is just that the PDF output is _displayed_, but actually all formats were generated. You can verify this by deleting the `_book` directory and clicking the Build Book button again, and you should see PDF, EPUB, and HTML files under the `_book` directory.

**Comment by slonik-az** [comment]
Unfortunately it is not the case. After I cleaned _book directory and rerun by clicking on 'knitr' button the _book directory contains only PDF and TEX files
$ ls -1 _book
bookdown-demo.pdf
bookdown-demo.tex

Also from the output in the 'R markdown window' I only see latex processing chain
`pandoc +RTS -K512m -RTS bookdown-demo.utf8.md --to latex`
Nothing about html.

**Comment by slonik-az** [comment]
It seems that the first entry in _output.yml defines the default output type used when knitr button is clicked. I reordered the entries making html output first.  Now it is a new default:

## _output.yml
```
bookdown::gitbook:
  css: style.css
  config:
    toc:
      before: |
        <li><a href="./">A Minimal Book Example</a></li>
      after: |
        <li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
    edit: https://github.com/rstudio/bookdown-demo/edit/master/%s
bookdown::pdf_book:
  includes:
    in_header: preamble.tex
  latex_engine: xelatex
  citation_package: natbib
  keep_tex: yes
bookdown::epub_book: default
```

**Comment by yihui** [comment]
You are right about the order of the formats in `_output.yml`, but I said "click the **Build Book** button" instead of the Knit button, and I showed a screenshot above.
