### ISSUE TITLE
Only non-empty .html file in _book is index.html

### ISSUE THREAD

**Issue by strakaps** [rstudio/bookdown-demo#15]
Hi,
when knitting this minimal example, all html files in `_book/` are empty, except `index.html`, which looks ok. 
bookdown: v0.4
RStudio: v1.0.143
devtools: 1.13.2
R: 3.4.0
knitr: 1.16
pandoc: 1.19.2.1
(on mac OS 10.12.5). 
Any hints?

**Comment by strakaps** [comment]
Tried `render_book(".")` and it worked. (Before I had just hit the "Knit" button on index.Rmd...)

**Comment by yihui** [comment]
You should open the RStudio project `bookdown-demo.Rproj`.

**Comment by strakaps** [comment]
Ah, ok. Thanks @yihui
