### ISSUE TITLE
Figures not referenced with consecutive numbers

### ISSUE THREAD

**Issue by amsantac** [rstudio/bookdown-demo#17]
I am testing the bookdown-demo and finding some problems with how additional figures are referenced.

I added a new figure:

'''{r nice2-fig, fig.cap='Here is a nice figure!', out.width='80%', fig.asp=.75, fig.align='center'}
par(mar = c(4, 4, .1, .1))
plot(pressure, type = 'b', pch = 19)
'''

but then the reference (Figure \@ref(fig:nice2-fig)) says Figure 3 instead of Figure 2. Is there any way to fix it? Thank you.

**Comment by amsantac** [comment]
I just updated the packages and the issue is not happening anymore. 

Thanks for your great contribution!

**Comment by yihui** [comment]
Glad to know the "[when in doubt, upgrade](https://yihui.name/en/2017/05/when-in-doubt-upgrade/)" strategy worked again.
