### ISSUE TITLE
Delete DESCRIPTION file

### ISSUE THREAD

**Issue by trestletech** [rstudio/bookdown-demo#18]
DESCRIPTION files currently confuse rsconnect and can make deploys not work properly. It looks like the DESCRIPTION file in this repo isn't actively being used; would it be safe to delete it?

(We're talking separately about changing rsconnect so that DESCRIPTION files don't break things.)

**Comment by yihui** [comment]
It is a hack to specify dependencies for Travis. Technically I can replace it with another way, but unfortunately I documented it in the bookdown book, which has been published last year: https://bookdown.org/yihui/bookdown/github.html

If that is too much trouble for you, I'll just delete it and revise the documentation, even though I cannot change the hardcopies of the book.

**Comment by trestletech** [comment]
Sounds like we need to update the behavior in rsconnect, then. I'll see what we can do about that. Thanks.

**Comment by trestletech** [comment]
Moved to https://github.com/rstudio/rsconnect/issues/192

**Comment by kevinushey** [comment]
FWIW the logic Packrat uses is here:

https://github.com/rstudio/packrat/blob/master/R/dependencies.R#L474-L494

Can you set the `Type:` field in the DESCRIPTION file to something not equal to `Package`? Or does that break existing workflows?

**Comment by yihui** [comment]
@kevinushey That is a great idea! I'll do it.

**Comment by kevinushey** [comment]
It looks like Travis failed, but perhaps for an unrelated reason? https://travis-ci.org/rstudio/bookdown-demo/builds/256202125?utm_source=github_status&utm_medium=notification

**Comment by yihui** [comment]
Yeah I just fixed it. Specifying `Type: Book` worked perfectly.

**Comment by kevinushey** [comment]
Awesome! 😄
