### ISSUE TITLE
Equations not show correctly with epub minimal ebook example

### ISSUE THREAD

**Issue by rbali** [rstudio/bookdown-demo#20]
Thanks for the package!
I was trying to create the epub version for the minimal example, but the equation $a^2 + b^2 = c^2$ is not printed correctly with the epub format. Instead I get "a2+b2=c2a^2 + b^2 = c^2." All other formats works well. 

Any ideias where to look to sove the problem?

**Comment by yihui** [comment]
What is your EPUB reader? At least Calibre and iBooks should render math expressions well: https://bookdown.org/yihui/bookdown/e-books.html

**Comment by rbali** [comment]
You are right, i was using the Microsoft edge's add on. Now I tested epubreader on Firefox and it renders everything well.

Thanks!
