### ISSUE TITLE
Epub output does not contain the diagram

### ISSUE THREAD

**Issue by jerrythomas** [rstudio/bookdown-demo#21]
When generating the epub output 

OS: macOS Sierra 10.12.6 
RStudio Server 1.0.153
R: 3.4.2
MacTex

Build options 
Project Build tools <website>
Book output format <bookdown::epub_book>
[bookdown-demo.epub.zip](https://github.com/rstudio/bookdown-demo/files/1452693/bookdown-demo.epub.zip)

Is this a bookdown issue or issue with code in this demo? The PDF output contains the diagram.

**Comment by yihui** [comment]
Please make sure you are not using Pandoc 2.0: https://github.com/rstudio/bookdown/issues/479

**Comment by jerrythomas** [comment]
You are right. Downgraded pandoc to 1.19.2.1 and it works perfectly now. Thanks.
