### ISSUE TITLE
Build book

### ISSUE THREAD

**Issue by Monduiz** [rstudio/bookdown-demo#24]
I installed bookdown but I don't have a build book command. Did I miss something?

I also can't build using cmd+shift+B.

RStudio version 1.1.383
R version 3.4.2 (2017-09-28)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.1

devtools_1.13.3
bookdown_0.5.10

**Comment by yihui** [comment]
Open the RStudio project (`bookdown-demo.Rproj`) instead of a single Rmd file.
