### ISSUE TITLE
render_book for pdf_book doesn't take into account config_file = "_bookdown.yml"

### ISSUE THREAD

**Issue by DDDSt** [rstudio/bookdown-demo#29]
Dear Yihui,

Thank you for the nice tool.

I am finishing the book in R about R and I am trying to compile it: 
render_book("index.Rmd", output_format = "bookdown::gitbook", clean = TRUE,
            envir = parent.frame(), clean_envir = !interactive(),
            output_dir = NULL, new_session = NA, preview = FALSE,
            encoding = "UTF-8", config_file = "_bookdown.yml")

Internalization (language change in "_bookdown.yml") works very well for output_format = "bookdown::gitbook", but not for output_format = "bookdown::pdf_book". For pdf_book "Chapter" remains "Chapter", as well as Figures, Tables...

I am struggling with that for some time without success. Do you have any suggestion.

Kind regards
Dejan

**Comment by yihui** [comment]
You need to use LaTeX tools: https://bookdown.org/yihui/bookdown/internationalization.html
