### ISSUE TITLE
pdf / epub formats

### ISSUE THREAD

**Issue by LiNk-NY** [rstudio/bookdown-demo#30]
Hi YiHui, @yihui

The building of the other formats `pdf` and `epub` is not shown in the
[_build.sh](https://github.com/rstudio/bookdown-demo/blob/master/_build.sh) file, although you are able to download either format from
the download button on the website. How was this done? Perhaps the `_build.sh` should file read:

```
Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book')"
Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::epub_book')"
```

These file formats do not appear in the `gh-pages` branch either. 

Thanks for your time!
Marcel

**Comment by yihui** [comment]
The version at https://bookdown.org/yihui/bookdown-demo was not built using `_build.sh` but simply `bookdown::render_book('index.Rmd')` (which renders to three formats specified in `_output.yml`). If you need PDF and EPUB, you need to do what you mentioned above or `bookdown::render_book('index.Rmd')`.
