### ISSUE TITLE
EPUB output do not have figure and table identifiers while compiling bookdown-demo book

### ISSUE THREAD

**Issue by N0rbert** [rstudio/bookdown-demo#42]
# Steps to reproduce
1. Have Ubuntu 18.04.2 LTS installed
1. Install latest [`pandoc-2.7.2-1-amd64.deb`](https://github.com/jgm/pandoc/releases/download/2.7.2/pandoc-2.7.2-1-amd64.deb) with
 
       cd ~/Downloads
       wget https://github.com/jgm/pandoc/releases/download/2.7.2/pandoc-2.7.2-1-amd64.deb
       sudo apt install ./pandoc-2.7.2-1-amd64.deb

1. Install R with `sudo apt-get install r-base-dev`
1. Launch R console to install `bookdown` package:

       $ R
       install.packages('bookdown')

1. Clone `bookdown-demo` repository

       sudo apt-get install git
       git clone https://github.com/rstudio/bookdown-demo.git
       cd bookdown-demo

1. Compile the demo book to EPUB format

       Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::epub_book')"

1. Install `epubcheck` with `sudo apt-get install epubcheck default-jre` and launch it against the compiled epub document:

       epubcheck _book/bookdown-demo.epub

Expected result - the produced EPUB document is correct and do not have errors

Actual result - the produced EPUB document has errors:

```
Validating using EPUB version 3.0.1 rules.
WARNING(ACC-009): _book/bookdown-demo.epub/EPUB/text/ch001.xhtml(82,446): MathML should either have an 'alttext' attribute or 'annotation-xml' child element.
ERROR(RSC-005): _book/bookdown-demo.epub/EPUB/text/ch002.xhtml(87,74): Error while parsing file 'value of attribute "width" is invalid; must be an integer'.
ERROR(RSC-012): _book/bookdown-demo.epub/EPUB/text/ch002.xhtml(82,247): Fragment identifier is not defined.
ERROR(RSC-012): _book/bookdown-demo.epub/EPUB/text/ch002.xhtml(92,123): Fragment identifier is not defined.
ERROR(RSC-012): _book/bookdown-demo.epub/EPUB/text/ch002.xhtml(92,252): Fragment identifier is not defined.

Check finished with errors

epubcheck completed
```

and user can't click on table and image references.
The problematic lines may be determined by unzipping epub and showing its contents:

```
cd _book
unzip bookdown-demo.epub
pluma EPUB/text/ch002.xhtml

$ awk 'NR==82' EPUB/text/ch002.xhtml
<p>You can label chapter and section titles using <code>{#label}</code> after them, e.g., we can reference Chapter <a href="#intro">2</a>. If you do not manually label them, there will be automatic labels anyway, e.g., Chapter <a href="#methods">4</a>.</p>

$ awk 'NR==92' EPUB/text/ch002.xhtml
<p>Reference a figure by its code chunk label with the <code>fig:</code> prefix, e.g., see Figure <a href="#fig:nice-fig">2.1</a>. Similarly, you can reference tables generated from <code>knitr::kable()</code>, e.g., see Table <a href="#tab:nice-tab">2.1</a>.</p>

```

Notes:
1. Issue persists with Pandoc 1.19 from the repository.
1. I'm not sure about correct component to report bug. Should it be `bookdown`, `rmarkdown`, `knitr` or `pandoc`?

**Comment by muschellij2** [comment]
I'm getting the same issues with our book on Leanpub, but it uploads OK.  I think it's bookdown, but I don't know what's going on with the ePub rendering.

**Comment by N0rbert** [comment]
I have received notification about bug 766, which is now locked.

So I'll write my test result here. OS is Debian 12, R is 4.2, pandoc is 2.17.1.1, R packages are the following:

```
> xfun::session_info('bookdown')
R version 4.2.2 Patched (2022-11-10 r83330)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 12 (bookworm)

Locale:
  LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
  LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
  LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
  LC_PAPER=en_US.UTF-8       LC_NAME=C                 
  LC_ADDRESS=C               LC_TELEPHONE=C            
  LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

Package version:
  base64enc_0.1.3   bookdown_0.36     bslib_0.5.1       cachem_1.0.8     
  cli_3.6.1         digest_0.6.33     ellipsis_0.3.2    evaluate_0.23    
  fastmap_1.1.1     fontawesome_0.5.2 fs_1.6.3          glue_1.6.2       
  graphics_4.2.2    grDevices_4.2.2   highr_0.10        htmltools_0.5.7  
  jquerylib_0.1.4   jsonlite_1.8.7    knitr_1.45        lifecycle_1.0.3  
  magrittr_2.0.3    memoise_2.0.1     methods_4.2.2     mime_0.12        
  R6_2.5.1          rappdirs_0.3.3    rlang_1.1.1       rmarkdown_2.25   
  sass_0.4.7        stats_4.2.2       stringi_1.7.12    stringr_1.5.0    
  tinytex_0.48      tools_4.2.2       utils_4.2.2       vctrs_0.6.4      
  xfun_0.41         yaml_2.3.7       
> 
```

The result of `epubcheck` 3.2 is the following:

```
$ epubcheck _book/*.epub
Validating using EPUB version 3.2 rules.
ERROR(RSC-005): _book/bookdown-demo.epub/EPUB/text/ch002.xhtml(152,74): Error while parsing file: value of attribute "width" is invalid; must be an integer
ERROR(RSC-012): _book/bookdown-demo.epub/EPUB/text/ch002.xhtml(147,247): Fragment identifier is not defined.

Check finished with errors
Messages: 0 fatals / 2 errors / 0 warnings / 0 infos

EPUBCheck completed
```

So 2 issues with EPUB still exist.
