### ISSUE TITLE
 bad restore file magic number

### ISSUE THREAD

**Issue by sliptonic** [rstudio/bookdown-demo#43]
I've installed Rstudio Version 1.1.463
R version 3.2.3
Linux Mint 18

I tried opening an older project that I haven't touched in a few months and got the error below.
I retried using the bookdown demo and got the same error.  
How can I resolve this?

I tried a more current version of rstudio but it fails on mint with an libssl error.  

> load("~/bookdown-demo/bookdown-demo.Rproj")
Error: bad restore file magic number (file may be corrupted) -- no data loaded
In addition: Warning message:
file ‘bookdown-demo.Rproj’ has magic number 'Versi'
  Use of save versions prior to 2 is deprecated

**Comment by yihui** [comment]
Why `load("~/bookdown-demo/bookdown-demo.Rproj")`? This file is not supposed to be `load()`ed into R.

**Comment by sliptonic** [comment]
Call it a long-day, late night, brain fart and accept my apologies.  I almost never use RStudio directly but build from a script instead.  The RStudio gui had me confused and I was trying to load the project file in the wrong window.

**Comment by yihui** [comment]
No worries!
