### ISSUE TITLE
Unable to "Build Book" at very start of book

### ISSUE THREAD

**Issue by erstearns** [rstudio/bookdown-demo#45]
Hello there,

I just forked and cloned this repo, installed TinyTeX and tried building the book as instructed, however I encountered the following error (I got the same error before installing TinyTeX as well):

````
processing file: bookdown-demo.Rmd
output file: bookdown-demo.knit.md

Error: Failed to compile bookdown-demo.tex. See https://yihui.name/tinytex/r/#debugging for debugging tips.
In addition: Warning message:
In system2(..., stdout = if (use_file_stdout()) f1 else FALSE, stderr = f2) :
  '"xelatex"' not found
Execution halted

Exited with status 1.
````

Your help resolving this is greatly appreciated. Awesome tool!

**Comment by yihui** [comment]
What does `tinytex::tinytex_root()` return?

**Comment by erstearns** [comment]
That returns an empty string:

````
> tinytex::tinytex_root()
[1] ""
````

**Comment by yihui** [comment]
So it seems you didn't install TinyTeX successfully. What is the output of `tinytex::install_tinytex()`?

**Comment by erstearns** [comment]
Woohoo! That worked! I did get a system error about the luatex.dll file not being found(see below), however when I re-ran the "Build book" call after installing as you suggested, the book rendered. Thank you very much for your help! 

![image](https://user-images.githubusercontent.com/25041596/63434402-dc214c00-c3d9-11e9-973d-9e44096a5a70.png)

**Comment by yihui** [comment]
The error dialog can be safely ignored, and was mentioned at https://yihui.name/tinytex/#installation. Thanks!
