### ISSUE TITLE
Suggestion: change this to a template repository in settings

### ISSUE THREAD

**Issue by jtr13** [rstudio/bookdown-demo#51]
As such, users would not need to get the whole commit history and could choose a new name for the repo when creating it.

**Comment by yihui** [comment]
Done. Thanks for the suggestion!

**Comment by jtr13** [comment]
My template has a green "Use this template" button and a template label next to the repo name: https://github.com/jtr13/EDAVproject 

I don't see that on this repo, not sure why.

**Comment by yihui** [comment]
For some reason Github didn't remember my choice after I clicked the checkbox in the repo settings. I just did it again, and now I can see "Use this template". Thanks again!

**Comment by jtr13** [comment]
I see it now, thank you!
