### ISSUE TITLE
Typo in latex code

### ISSUE THREAD

**Issue by pbreheny** [rstudio/bookdown-demo#74]
This line has parenthesis instead of curly braces:

https://github.com/rstudio/bookdown-demo/blob/ec6a068aa4bce294011f199c3abcfcf10127e846/03-method.Rmd#L12

should be

```tex
SE = \sqrt{\frac{p(1-p)}{n}} \approx \sqrt{\frac{1/3 (1 - 1/3)} {300}} = 0.027 
```

The same mistake happens later in the same file:

https://github.com/rstudio/bookdown-demo/blob/ec6a068aa4bce294011f199c3abcfcf10127e846/03-method.Rmd#L22

**Comment by yihui** [comment]
Fixed now. Thanks for the report!
